# Generated by Django 6.0.1 on 2026-01-07 03:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='WhatsApp ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('BROWSING', 'Browsing Raffles'), ('SELECTING_NUMBERS', 'Selecting Numbers'), ('CONFIRMING_ORDER', 'Confirming Order'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('UPLOADING_PROOF', 'Uploading Payment Proof')], db_index=True, default='IDLE', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_interaction_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['-last_interaction_at'],
                'indexes': [models.Index(fields=['-last_interaction_at'], name='whatsapp_wh_last_in_5dc992_idx'), models.Index(fields=['state', '-last_interaction_at'], name='whatsapp_wh_state_1ed530_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='WhatsApp Message ID')),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive', 'Interactive'), ('button', 'Button'), ('unknown', 'Unknown')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Inbound Message',
                'verbose_name_plural': 'Inbound Messages',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='whatsapp_in_receive_0193c9_idx'), models.Index(fields=['contact', '-received_at'], name='whatsapp_in_contact_64c54e_idx'), models.Index(fields=['processed', '-received_at'], name='whatsapp_in_process_ca1453_idx')],
            },
        ),
    ]
