# Generated by Django 5.2.10 on 2026-01-08 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'Mensaje Entrante', 'verbose_name_plural': 'Mensajes Entrantes'},
        ),
        migrations.AlterModelOptions(
            name='whatsappcontact',
            options={'ordering': ['-last_interaction_at'], 'verbose_name': 'Contacto de WhatsApp', 'verbose_name_plural': 'Contactos de WhatsApp'},
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcontact', verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de media'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Ubicación'), ('contacts', 'Contactos'), ('interactive', 'Interactivo'), ('button', 'Botón'), ('unknown', 'Desconocido')], default='text', max_length=20, verbose_name='tipo de mensaje'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='procesado'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='payload crudo'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='wa_message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID de mensaje de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='context',
            field=models.JSONField(blank=True, default=dict, verbose_name='contexto'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='last_interaction_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='última interacción'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Inactivo'), ('BROWSING', 'Explorando Rifas'), ('SELECTING_NUMBERS', 'Seleccionando Números'), ('CONFIRMING_ORDER', 'Confirmando Orden'), ('AWAITING_PAYMENT', 'Esperando Pago'), ('UPLOADING_PROOF', 'Subiendo Comprobante')], db_index=True, default='IDLE', max_length=30, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='wa_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID de WhatsApp'),
        ),
    ]
