# Generated by Django 5.2.10 on 2026-01-08 21:18

from django.db import migrations


def set_default_tenant(apps, schema_editor):
    """Assign the default tenant to all existing WhatsApp contacts."""
    Tenant = apps.get_model('core', 'Tenant')
    WhatsAppContact = apps.get_model('whatsapp', 'WhatsAppContact')

    try:
        default_tenant = Tenant.objects.get(slug='default')

        # Update all contacts without a tenant
        WhatsAppContact.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    except Tenant.DoesNotExist:
        # If default tenant doesn't exist, skip (shouldn't happen in normal flow)
        pass


def reverse_set_default_tenant(apps, schema_editor):
    """Set tenant to NULL when rolling back."""
    WhatsAppContact = apps.get_model('whatsapp', 'WhatsAppContact')
    WhatsAppContact.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('whatsapp', '0002_alter_inboundmessage_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_tenant, reverse_set_default_tenant),
    ]
