# Generated by Django 5.2.10 on 2026-01-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('whatsapp', '0003_set_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcontact',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['tenant', '-last_interaction_at'], name='whatsapp_wh_tenant__877fb2_idx'),
        ),
    ]
