# Generated by Django 5.2.10 on 2026-01-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único del tenant (usado en URLs)', unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configuraciones personalizadas del tenant', verbose_name='configuración')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL del logo')),
                ('plan', models.CharField(default='basic', max_length=50, verbose_name='plan')),
                ('max_appointments_per_month', models.IntegerField(default=1000, help_text='Límite de citas que puede crear por mes', verbose_name='máximo de citas por mes')),
                ('max_raffles', models.IntegerField(default=10, help_text='Límite de rifas activas simultaneas', verbose_name='máximo de rifas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='core_tenant_slug_9abdcd_idx'), models.Index(fields=['is_active', '-created_at'], name='core_tenant_is_acti_062958_idx')],
            },
        ),
    ]
