# Generated by Django 5.2.10 on 2026-01-08 21:16

from django.db import migrations


def create_default_tenant(apps, schema_editor):
    """Create a default tenant for existing data."""
    Tenant = apps.get_model('core', 'Tenant')
    Tenant.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'plan': 'basic',
        }
    )


def reverse_create_default_tenant(apps, schema_editor):
    """Remove the default tenant if rolling back."""
    Tenant = apps.get_model('core', 'Tenant')
    Tenant.objects.filter(slug='default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_tenant, reverse_create_default_tenant),
    ]
