# Generated by Django 6.0.1 on 2026-01-07 03:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('min_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('winner_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Raffle',
                'verbose_name_plural': 'Raffles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='raffles_raf_is_acti_2e263c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('payment_proof_media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='whatsapp.whatsappcontact')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold')], db_index=True, default='AVAILABLE', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles.raffle')),
                ('reserved_by_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_tickets', to='raffles.order')),
            ],
            options={
                'verbose_name': 'Ticket Number',
                'verbose_name_plural': 'Ticket Numbers',
                'ordering': ['raffle', 'number'],
            },
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='raffles.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='raffles.ticketnumber')),
            ],
            options={
                'verbose_name': 'Order Ticket',
                'verbose_name_plural': 'Order Tickets',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='raffles_ord_status_05ea4e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contact', '-created_at'], name='raffles_ord_contact_a3e87d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['raffle', '-created_at'], name='raffles_ord_raffle__3ac274_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='raffles_ord_status_51b5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketnumber',
            index=models.Index(fields=['raffle', 'status'], name='raffles_tic_raffle__2db3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketnumber',
            index=models.Index(fields=['status', 'reserved_until'], name='raffles_tic_status_d12c8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketnumber',
            unique_together={('raffle', 'number')},
        ),
        migrations.AddIndex(
            model_name='orderticket',
            index=models.Index(fields=['order', 'ticket'], name='raffles_ord_order_i_5c99ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderticket',
            unique_together={('order', 'ticket')},
        ),
    ]
