# Generated by Django 5.2.10 on 2026-01-08 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('raffles', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='orderticket',
            options={'verbose_name': 'Boleto de Orden', 'verbose_name_plural': 'Boletos de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='raffle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.AlterModelOptions(
            name='ticketnumber',
            options={'ordering': ['raffle', 'number'], 'verbose_name': 'Número de Boleto', 'verbose_name_plural': 'Números de Boletos'},
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='whatsapp.whatsappcontact', verbose_name='contacto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof_media_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='raffles.raffle', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_PAYMENT', 'Pendiente de Pago'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], db_index=True, default='DRAFT', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='raffles.order', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='raffles.ticketnumber', verbose_name='boleto'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='draw_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha del sorteo'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='max_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número máximo'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='min_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número mínimo'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio del boleto'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='número ganador'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffles.raffle', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='reserved_by_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_tickets', to='raffles.order', verbose_name='reservado por orden'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='reserved_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='reservado hasta'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='ticketnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
    ]
