# Generated by Django 5.2.10 on 2026-01-08 21:18

from django.db import migrations


def set_default_tenant(apps, schema_editor):
    """Assign the default tenant to all existing raffles and orders."""
    Tenant = apps.get_model('core', 'Tenant')
    Raffle = apps.get_model('raffles', 'Raffle')
    Order = apps.get_model('raffles', 'Order')

    try:
        default_tenant = Tenant.objects.get(slug='default')

        # Update all raffles without a tenant
        Raffle.objects.filter(tenant__isnull=True).update(tenant=default_tenant)

        # Update all orders without a tenant
        Order.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    except Tenant.DoesNotExist:
        # If default tenant doesn't exist, skip (shouldn't happen in normal flow)
        pass


def reverse_set_default_tenant(apps, schema_editor):
    """Set tenant to NULL when rolling back."""
    Raffle = apps.get_model('raffles', 'Raffle')
    Order = apps.get_model('raffles', 'Order')

    Raffle.objects.all().update(tenant=None)
    Order.objects.all().update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('raffles', '0002_alter_order_options_alter_orderticket_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_tenant, reverse_set_default_tenant),
    ]
