# Generated by Django 5.2.10 on 2026-01-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_tenant'),
        ('raffles', '0003_set_default_tenant'),
        ('whatsapp', '0003_set_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='core.tenant', verbose_name='tenant'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='raffles_ord_tenant__3b197b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', '-created_at'], name='raffles_ord_tenant__400353_idx'),
        ),
        migrations.AddIndex(
            model_name='raffle',
            index=models.Index(fields=['tenant', 'is_active', '-created_at'], name='raffles_raf_tenant__4a7e00_idx'),
        ),
    ]
