# Generated by Django 5.2.10 on 2026-01-08 22:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('BANCARD', 'Bancard'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20, verbose_name='proveedor')),
                ('external_id', models.CharField(db_index=True, help_text='ID de la transacción en el proveedor de pago', max_length=255, verbose_name='ID externo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='moneda')),
                ('status', models.CharField(db_index=True, help_text='Estado de la transacción: pending, paid, failed, refunded', max_length=20, verbose_name='estado')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa del proveedor de pago', verbose_name='respuesta cruda')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='tipo de contenido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='payments_pa_tenant__a50b2c_idx'), models.Index(fields=['external_id'], name='payments_pa_externa_e91e0b_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_a2ce56_idx'), models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_51b568_idx')],
            },
        ),
    ]
