# Generated by Django 5.2.10 on 2026-01-08 21:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_create_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('last_appointment_at', models.DateTimeField(blank=True, help_text='Fecha de la última cita completada', null=True, verbose_name='última cita')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('duration_minutes', models.IntegerField(help_text='Duración del servicio en minutos', validators=[django.core.validators.MinValueValidator(5)], verbose_name='duración (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='moneda')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('buffer_time_minutes', models.IntegerField(default=0, help_text='Tiempo de preparación antes/después de la cita', validators=[django.core.validators.MinValueValidator(0)], verbose_name='tiempo de buffer (minutos)')),
                ('max_bookings_per_day', models.IntegerField(default=20, help_text='Número máximo de citas de este servicio por día', validators=[django.core.validators.MinValueValidator(1)], verbose_name='máximo de reservas por día')),
                ('advance_booking_days', models.IntegerField(default=30, help_text='Cuántos días de anticipación se puede reservar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='días de anticipación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='fecha programada')),
                ('duration_minutes', models.IntegerField(help_text='Duración denormalizada del servicio', verbose_name='duración (minutos)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=20, verbose_name='estado')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('REFUNDED', 'Reembolsado')], db_index=True, default='PENDING', max_length=20, verbose_name='estado de pago')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='moneda')),
                ('payment_proof_media_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de comprobante de pago')),
                ('bancard_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID transacción Bancard')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID evento Google Calendar')),
                ('customer_notes', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.tenant', verbose_name='tenant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.customer', verbose_name='cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'phone'], name='appointment_tenant__d1df78_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='appointment_tenant__d230f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', '-last_appointment_at'], name='appointment_tenant__a08970_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_active'], name='appointment_tenant__7be86c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', '-created_at'], name='appointment_tenant__2ee711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='appointment_tenant__7dfb71_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='appointment_tenant__a13699_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service', 'scheduled_at'], name='appointment_service_384ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', '-created_at'], name='appointment_custome_0865bb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'payment_status'], name='appointment_status_8653b7_idx'),
        ),
    ]
